config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sales', to: 'quotes#sales', as: 'sales'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get 'home/index'
  root 'home#index'

  resources :quotes do
    collection do
      get 'final_price'
    end
  end

  resources :loans do
    member do
      get 'loan_interestrate'
    end
  end

  resources :roles
  resources :customers
  resources :searches

  resources :cars do
    member do
      get 'wholesale_price'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    user ||= User.new # guest user (not logged in)
    cannot :read, :all # Guest

    if user.role == "admin"
    can :manage, :all
    end

    if user.role == "dealership_owner"
      can :manage, :all
    end

    if user.role == "sales_manager"
      can :manage, Sale
      can :manage, Quote
      can :manage, Customer
      can :read, Loan
      can :read, Car
    end

    if user.role == "finance_manager"
      can :manage, Quote
      can :manage, Loan
      can :manage, Quotesold
      can :read, Customer
      can :read, Car
    end

    if user.role == "inventory_manager"
      can :manage, Car
    end

    if user.role == "sales_person"
      can :manage, Quote
      can :manage, Customer
      can :read, Car
      can :read, Loan
    end


#TODO ADD THESE AUTHORIZATIONS

    # Define abilities for the passed in user here. For example
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  validates_presence_of :make, :model, :color, :vin, :wholesaleprice, :image
  validates_numericality_of :wholesaleprice, greater_than_or_equal_to:0

  def full_car
    "#{vin} - #{make} #{model}"
  end

  def car_box
    "#{color} #{make} #{model}"
  end

  before_create :add_default_car_img, on: [:create, :update]

  private def add_default_car_img
    unless image.attached?
      self.image.attach(io: File.open('app/assets/images/inception images/default-car.jpg'), filename: 'default-car.jpg', content_type: 'image/jpg')
    end
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates_numericality_of :interestrate, greater_than_or_equal_to:0

  YEARS = %i[3 4 5]

  def full_name
    "#{year} years - #{interestrate * 100}%"
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  belongs_to :car
  belongs_to :loan

  def helper
    wholesale = wholesaleprice
  end

  def sold_to_string
    sold ? 'Sold' : 'Not Sold'
  end

  def self.calc_final_price(car_id, loan_id)
    car = Car.find(car_id)
    loan = Loan.find(loan_id)

    principle = car.wholesaleprice
    rate = loan.interestrate
    years = loan.year

    r = rate / 4;
    n = years * 4;

    markupPrice = principle * 1.082
    taxPrice = markupPrice * 1.043

    total_price = taxPrice*((1+r)**n)

    return total_price
  end

  def sum
    inject(0) { |sum, x| sum + x }
  end
end

app/models/quotesold.rb
class Quotesold < ApplicationRecord

end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
# This currently has no functionality, but is a shell for advanced search.
  def search_cars

    cars = Car.all

    cars = cars.where(["name LIKE ?","%#{keyword}%"]) if keyword.present?
    cars = cars.where(["make LIKE ?", make]) if make.present?
    cars = cars.where(["model LIKE ?", model]) if model.present?
    cars = cars.where(["color LIKE ?", color]) if color.present?
    cars = cars.where(["wholesaleprice >= ?", minprice]) if minprice.present?
    cars = cars.where(["wholesaleprice >= ?", maxprice]) if maxprice.present?
    cars = cars.where(["vin LIKE ?", vin]) if vin.present?

    return cars
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_presence_of :firstname, :lastname, :email, :role


  ROLES = %i[admin dealership_owner sales_person sales_manager finance_manager inventory_manager]

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  load_and_authorize_resource
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  def final_price
    quote_car_id = params[:car]
    quote_loan_id = params[:loan]
    finalPrice = Quote.calc_final_price(quote_car_id, quote_loan_id)
    render json: {price: finalPrice}
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quotes = Quote.all
    respond_to do |format|
      format.html
      format.json
      format.pdf {
        render template: 'quotes/quotereport',
               pdf: 'QuoteReport'
      }
    end
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:totalprice, :multiplier, :customer_id, :user_id, :sold, :car_id, :loan_id, :wholesaleprice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <thead>
    </thead>
    <tbody>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Customer: " %></td>
          <td><%= form.collection_select :customer_id, Customer.all, :id, :full_name %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Employee: " %></td>
          <td><%= form.collection_select :user_id, User.all, :id, :full_name %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Car: " %></td>
          <td><%= form.collection_select :car_id, Car.all, :id, :full_car %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Wholesale Price: $" %></td>
          <td><%= form.text_field :wholesaleprice, :id=>'wholesaleprice', :class=>'form-control' %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Markup Value: %" %></td>
          <td><%= form.text_field :multiplier, :value => 8.2 %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <td><p><strong>Subtotal Price: </strong></p></td>
        <td><p>$<span id="subtotalprice"></span></p></td></td>
      </tr>
      <tr class="spaceUnder">
        <td><p><strong>Sales Tax: </strong></p></td>
        <td>4.3%</td>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Loan: " %></td>
          <td><%= form.collection_select :loan_id, Loan.all, :id, :full_name %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Total Price: $" %></td>
          <td><%= form.text_field :totalprice, :id=>'totalprice', :class=>'form-control' %></td>
        </div>
      </tr>
      <% if can? :manage, Quotesold %>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Sold: " %></td>
          <td><%= form.check_box :sold %></td>
        </div>
      </tr>
      <%end %>
    </tbody>
  </table>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Employee</th>
      <th>Car</th>
      <th>Wholesale Price</th>
      <th>Loan</th>
      <th>Multiplier</th>
      <th>Total Price</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.user.full_name %></td>
        <td><%= quote.car.full_car %></td>
        <td><%= number_to_currency(quote.wholesaleprice) %></td>
        <td><%= quote.loan.full_name %></td>
        <td><%= number_to_percentage(quote.multiplier, precision: 2)%></td>
        <td><%= number_to_currency(quote.totalprice)%></td>
        <td><%= quote.sold_to_string %></td>
        <td>
          <div class="pure-menu pure-menu-horizontal">
            <ul class="pure-menu-list">
              <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                <a href="#" id="menuLink1" class="pure-menu-link">Options</a>
                <ul class="pure-menu-children">
                  <li class="pure-menu-item"><%= link_to 'Show', quote %></li>
                  <% if can? :manage, Quote %>
                  <li class="pure-menu-item"><%= link_to 'Edit', edit_quote_path(quote) %></li>
                  <li class="pure-menu-item"><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                    <%end %>
                </ul>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/quotereport.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    #header {
      border-bottom: 4px solid #99d3df;
      padding: 10px;
      margin: auto;
      text-align: center;
      background-color: #88bbd6;
      text-decoration-color: #ffffff;
      color: white;
    }
  </style>
  <div id="header">
    <img src="https://i.gyazo.com/ec2607e4bec4158f564f17f6ef0fbd5a.png">
  </div>
  <% wicked_pdf_stylesheet_link_tag 'pdf' %>
  <meta charset ="utf-8">
<h1>Quote</h1>
</head>

<br/>
<body style="text-align: center;">
<%=image_tag(@quote.car.image, style: 'width:440px;height:300px;')%>
<hr style="width: 65%;"/>
<h2>
  <strong>Customer:</strong>
  <%= @quote.customer.full_name %>
</h2>
<br/>
<h2>
  <strong>Employee:</strong>
  <%= @quote.user.full_name %>
</h2>
<br/>
<h2>
  <strong>Car:</strong>
  <%= @quote.car.full_car %>
</h2>
<br/>
<h2>
  <strong>Wholesale Price:</strong>
  <%= number_to_currency(@quote.wholesaleprice)%>
</h2>
<br/>
<h2>
  <strong>Loan:</strong>
  <%= @quote.loan.full_name %>
</h2>
<br/>
<h2>
  <strong>Multiplier:</strong>
  8.2%
</h2>
<br/>
<h2>
  <strong>Total Price:</strong>
  <%= number_to_currency(@quote.totalprice)%>
</h2>
<br/>
<h2>
  <strong>Monthly Payment:</strong>
  <%r = @quote.loan.interestrate / 12 %>
  <%n = @quote.loan.year * 12 %>
  <%=number_to_currency(@quote.totalprice * r/(1-(1/(1+r))**n)) %>
</h2>
<h1>
  <p style="color: red;"><%= @quote.sold_to_string %></p>
</h1>
</body>
</html>

app/views/quotes/sales.html.erb
<% if can? :manage, Sale %>
<p id="notice"><%= notice %></p>
<h1>Sales</h1>
<br>
  <% if can? :manage, Dealer %>
    <div class ="dealer">
      <h3>Sales Margins</h3>
      <table style="width: 500px;">
        <thead>
        <tr>
          <th>Gross Income</th>
          <th>Net Income</th>
          <th>Total Sales Tax</th>
        </tr>
        </thead>
        <tbody>
        <tr class="spaceUnder">
          <td><%= number_to_currency(@quotes.where(:sold=>true).sum( :totalprice)) %></td>
          <td><%= number_to_currency((@quotes.where(:sold=>true).sum( :totalprice)) - (@quotes.where(:sold=>true).sum(:wholesaleprice))) %></td>
          <td><%= number_to_currency(@quotes.where(:sold=>true).sum( :totalprice) * 0.043) %></td>
        </tr>
        </tbody>
      </table>
    </div>
    <hr style="width: 50%;"/>
  <% end %>

<div id = "salesmanager">
  <h3>Recent Sales by Employee</h3>
  <table style="width: 500px;">
    <thead>
    <tr>
      <th>Employee</th>
      <th>Amount Sold</th>
    </tr>
    </thead>
    <tbody>
      <%@quotes.where(:sold=>true).each do |quote|%>
      <tr class="spaceUnder">
        <td><%=quote.user.full_name%></td>
        <td><%=number_to_currency(quote.totalprice)%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<div id="left_side" style="float:left; padding-left: 350px; padding-bottom: 50px;">
  <%=image_tag(@quote.car.image, style: 'width:140px;height:100px;')%>
  <p>
    <strong>Customer:</strong>
    <%= @quote.customer.full_name %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= @quote.user.full_name %>
  </p>

  <p>
    <strong>Car:</strong>
    <%= @quote.car.full_car %>
  </p>

  <p>
    <strong>Wholesale Price:</strong>
    <%= number_to_currency(@quote.wholesaleprice)%>
  </p>

  <p>
    <strong>Loan:</strong>
    <%= @quote.loan.full_name %>
  </p>

  <p>
    <strong>Multiplier:</strong>
    8.2%
  </p>

  <p>
    <strong>Total Price:</strong>
    <%= number_to_currency(@quote.totalprice)%>
  </p>

  <p>
    <strong>Sold:</strong>
    <%= @quote.sold_to_string %>
  </p>
  <% if can? :manage, Quotesold %>
  <%= link_to 'Download PDF', quote_path(@quote, format: 'pdf'), taget: '_blank' %> |
    <%end %>
    <% if can? :manage, Quote %>
  <%= link_to 'Edit', edit_quote_path(@quote) %> |
    <%end %>
  <%= link_to 'Back', quotes_path %>
</div>
<div id="right_side" style="float: right; padding-right: 350px; padding-bottom: 50px; padding-top: 100px;">
  <table id="amortizedTable">
    <thead>
    </thead>
    <tbody>
      <tr class="spaceUnder">
        <td><b>Total Price:</b></td>
        <td><%=number_to_currency(@quote.totalprice)%></td>
      </tr>
      <tr class="spaceUnder">
        <td><b>Loan:</b></td>
        <td><%=@quote.loan.full_name %></td>
      </tr>
      <tr class="spaceUnder">
        <td><b>Interest Rate:</b></td>
        <td><%= (@quote.loan.interestrate)*100%>%</td>
      </tr>
      <tr class="spaceUnder">
        <td><b>Years:</b></td>
        <td><%= @quote.loan.year%></td>
      </tr>
      <tr class="spaceUnder">
        <td><b>Monthly Payment: </b></td>
        <td id="payment"><script>getPayment('<%=@quote.totalprice%>', '<%=@quote.loan.interestrate%>', '<%=@quote.loan.year%>', 12)</script></td>
      </tr>
    </tbody>
  </table>
</div>
<script>buildSchedule('<%=@quote.totalprice%>', '<%=@quote.loan.interestrate%>', '<%=@quote.loan.year%>', 12)</script>