config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sales', to: 'quotes#sales', as: 'sales'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get 'home/index'
  root 'home#index'

  resources :quotes do
    collection do
      get 'final_price'
    end
  end

  resources :loans do
    member do
      get 'loan_interestrate'
    end
  end

  resources :roles
  resources :customers
  resources :searches

  resources :cars do
    member do
      get 'wholesale_price'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    user ||= User.new # guest user (not logged in)
    cannot :read, :all # Guest

    if user.role == "admin"
    can :manage, :all
    end

    if user.role == "dealership_owner"
      can :manage, :all
    end

    if user.role == "sales_manager"
      can :manage, Sale
      can :manage, Quote
      can :manage, Customer
      can :read, Loan
      can :read, Car
    end

    if user.role == "finance_manager"
      can :manage, Quote
      can :manage, Loan
      can :manage, Quotesold
      can :read, Customer
      can :read, Car
    end

    if user.role == "inventory_manager"
      can :manage, Car
    end

    if user.role == "sales_person"
      can :manage, Quote
      can :manage, Customer
      can :read, Car
      can :read, Loan
    end


#TODO ADD THESE AUTHORIZATIONS

    # Define abilities for the passed in user here. For example
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  validates_presence_of :make, :model, :color, :vin, :wholesaleprice, :image
  validates_numericality_of :wholesaleprice, greater_than_or_equal_to:0

  def full_car
    "#{vin} - #{make} #{model}"
  end

  def car_box
    "#{color} #{make} #{model}"
  end

  before_create :add_default_car_img, on: [:create, :update]

  private def add_default_car_img
    unless image.attached?
      self.image.attach(io: File.open('app/assets/images/inception images/default-car.jpg'), filename: 'default-car.jpg', content_type: 'image/jpg')
    end
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates_numericality_of :interestrate, greater_than_or_equal_to:0

  YEARS = %i[3 4 5]

  def full_name
    "#{year} years - #{interestrate * 100}%"
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  belongs_to :car
  belongs_to :loan

  def helper
    wholesale = wholesaleprice
  end

  def sold_to_string
    sold ? 'Sold' : 'Not Sold'
  end

  def self.calc_final_price(car_id, loan_id)
    car = Car.find(car_id)
    loan = Loan.find(loan_id)

    principle = car.wholesaleprice
    rate = loan.interestrate
    years = loan.year

    r = rate / 4;
    n = years * 4;

    markupPrice = principle * 1.082
    taxPrice = markupPrice * 1.043

    total_price = taxPrice*((1+r)**n)

    return total_price
  end

  def sum
    inject(0) { |sum, x| sum + x }
  end
end

app/models/quotesold.rb
class Quotesold < ApplicationRecord

end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
# This currently has no functionality, but is a shell for advanced search.
  def search_cars

    cars = Car.all

    cars = cars.where(["name LIKE ?","%#{keyword}%"]) if keyword.present?
    cars = cars.where(["make LIKE ?", make]) if make.present?
    cars = cars.where(["model LIKE ?", model]) if model.present?
    cars = cars.where(["color LIKE ?", color]) if color.present?
    cars = cars.where(["wholesaleprice >= ?", minprice]) if minprice.present?
    cars = cars.where(["wholesaleprice >= ?", maxprice]) if maxprice.present?
    cars = cars.where(["vin LIKE ?", vin]) if vin.present?

    return cars
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_presence_of :firstname, :lastname, :email, :role


  ROLES = %i[admin dealership_owner sales_person sales_manager finance_manager inventory_manager]

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <thead>
    </thead>
    <tbody>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "First Name: " %></td>
          <td><%= form.text_field :firstname %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Last Name: " %></td>
          <td><%= form.text_field :lastname %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Email: " %></td>
          <td><%= form.text_field :email %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Password: " %></td>
          <td><%= form.password_field :password %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Password Confirmation: " %></td>
          <td><%= form.password_field :password_confirmation %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Role: " %></td>
          <td><%= form.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %></td>
        </div>
      </tr>
    </tbody>
  </table>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname%></td>
        <td><%= user.lastname%></td>
        <td><%= user.email %></td>
        <td><%= user.role.humanize %></td>
        <td>
          <div class="pure-menu pure-menu-horizontal">
            <ul class="pure-menu-list">
              <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                <a href="#" id="menuLink1" class="pure-menu-link">Options</a>
                <ul class="pure-menu-children">
                  <li class="pure-menu-item"><%= link_to 'Show', user %></li>
                  <li class="pure-menu-item"><%= link_to 'Edit', edit_user_path(user) %></li>
                  <li class="pure-menu-item"><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_user_path %>

app/views/users/new.html.erb
<h1>New Employee</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<strong>Full Name:</strong>
<%= @user.full_name %>
<br>
<strong>Email:</strong>
<%= @user.email %>
<br>
<strong>Role:</strong>
<%= @user.role.humanize %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>