config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sales', to: 'quotes#sales', as: 'sales'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get 'home/index'
  root 'home#index'

  resources :quotes do
    collection do
      get 'final_price'
    end
  end

  resources :loans do
    member do
      get 'loan_interestrate'
    end
  end

  resources :roles
  resources :customers
  resources :searches

  resources :cars do
    member do
      get 'wholesale_price'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    user ||= User.new # guest user (not logged in)
    cannot :read, :all # Guest

    if user.role == "admin"
    can :manage, :all
    end

    if user.role == "dealership_owner"
      can :manage, :all
    end

    if user.role == "sales_manager"
      can :manage, Sale
      can :manage, Quote
      can :manage, Customer
      can :read, Loan
      can :read, Car
    end

    if user.role == "finance_manager"
      can :manage, Quote
      can :manage, Loan
      can :manage, Quotesold
      can :read, Customer
      can :read, Car
    end

    if user.role == "inventory_manager"
      can :manage, Car
    end

    if user.role == "sales_person"
      can :manage, Quote
      can :manage, Customer
      can :read, Car
      can :read, Loan
    end


#TODO ADD THESE AUTHORIZATIONS

    # Define abilities for the passed in user here. For example
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  validates_presence_of :make, :model, :color, :vin, :wholesaleprice, :image
  validates_numericality_of :wholesaleprice, greater_than_or_equal_to:0

  def full_car
    "#{vin} - #{make} #{model}"
  end

  def car_box
    "#{color} #{make} #{model}"
  end

  before_create :add_default_car_img, on: [:create, :update]

  private def add_default_car_img
    unless image.attached?
      self.image.attach(io: File.open('app/assets/images/inception images/default-car.jpg'), filename: 'default-car.jpg', content_type: 'image/jpg')
    end
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates_numericality_of :interestrate, greater_than_or_equal_to:0

  YEARS = %i[3 4 5]

  def full_name
    "#{year} years - #{interestrate * 100}%"
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  belongs_to :car
  belongs_to :loan

  def helper
    wholesale = wholesaleprice
  end

  def sold_to_string
    sold ? 'Sold' : 'Not Sold'
  end

  def self.calc_final_price(car_id, loan_id)
    car = Car.find(car_id)
    loan = Loan.find(loan_id)

    principle = car.wholesaleprice
    rate = loan.interestrate
    years = loan.year

    r = rate / 4;
    n = years * 4;

    markupPrice = principle * 1.082
    taxPrice = markupPrice * 1.043

    total_price = taxPrice*((1+r)**n)

    return total_price
  end

  def sum
    inject(0) { |sum, x| sum + x }
  end
end

app/models/quotesold.rb
class Quotesold < ApplicationRecord

end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
# This currently has no functionality, but is a shell for advanced search.
  def search_cars

    cars = Car.all

    cars = cars.where(["name LIKE ?","%#{keyword}%"]) if keyword.present?
    cars = cars.where(["make LIKE ?", make]) if make.present?
    cars = cars.where(["model LIKE ?", model]) if model.present?
    cars = cars.where(["color LIKE ?", color]) if color.present?
    cars = cars.where(["wholesaleprice >= ?", minprice]) if minprice.present?
    cars = cars.where(["wholesaleprice >= ?", maxprice]) if maxprice.present?
    cars = cars.where(["vin LIKE ?", vin]) if vin.present?

    return cars
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_presence_of :firstname, :lastname, :email, :role


  ROLES = %i[admin dealership_owner sales_person sales_manager finance_manager inventory_manager]

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  load_and_authorize_resource
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  def loan_interestrate
    interestrate = Loan.find(params[:id])
    render json: interestrate
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:loanname, :year, :interestrate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
    </thead>
    <tbody>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Loan Name: " %></td>
          <td><%= form.text_field :loanname%></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Years: " %></td>
          <td><%= form.collection_select(:year, Loan::YEARS, :to_s, lambda{|i| i.to_s.humanize}) %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Interest Rate: " %></td>
          <td><%= form.text_field :interestrate %></td>
        </div>
      </tr>
    </tbody>
  </table>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loans</h1>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th>Loan Name</th>
      <th>Years</th>
      <th>Interest Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.loanname %></td>
        <td><%= loan.year %></td>
        <td><%= loan.interestrate * 100 %>%</td>
        <td>
          <div class="pure-menu pure-menu-horizontal">
            <ul class="pure-menu-list">
              <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                <a href="#" id="menuLink1" class="pure-menu-link">Options</a>
                <ul class="pure-menu-children">
                  <li class="pure-menu-item"><%= link_to 'Show', loan %></li>
                  <% if can? :manage, Loan %>
                  <li class="pure-menu-item"><%= link_to 'Edit', edit_loan_path(loan) %></li>
                  <li class="pure-menu-item"><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                    <%end %>
                </ul>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan', new_loan_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Loan Name:</strong>
  <%= @loan.loanname %>
</p>

<p>
  <strong>Years:</strong>
  <%= @loan.year %>
</p>

<p>
  <strong>Interest Rate:</strong>
  <%= @loan.interestrate %>
</p>
<% if can? :manage, Loan %>
<%= link_to 'Edit', edit_loan_path(@loan) %> |
  <%end %>
<%= link_to 'Back', loans_path %>