config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sales', to: 'quotes#sales', as: 'sales'

  resources :sessions, only: [:new, :create, :destroy]

  resources :users
  get 'home/index'
  root 'home#index'

  resources :quotes do
    collection do
      get 'final_price'
    end
  end

  resources :loans do
    member do
      get 'loan_interestrate'
    end
  end

  resources :roles
  resources :customers
  resources :searches

  resources :cars do
    member do
      get 'wholesale_price'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, to: :crud
    user ||= User.new # guest user (not logged in)
    cannot :read, :all # Guest

    if user.role == "admin"
    can :manage, :all
    end

    if user.role == "dealership_owner"
      can :manage, :all
    end

    if user.role == "sales_manager"
      can :manage, Sale
      can :manage, Quote
      can :manage, Customer
      can :read, Loan
      can :read, Car
    end

    if user.role == "finance_manager"
      can :manage, Quote
      can :manage, Loan
      can :manage, Quotesold
      can :read, Customer
      can :read, Car
    end

    if user.role == "inventory_manager"
      can :manage, Car
    end

    if user.role == "sales_person"
      can :manage, Quote
      can :manage, Customer
      can :read, Car
      can :read, Loan
    end


#TODO ADD THESE AUTHORIZATIONS

    # Define abilities for the passed in user here. For example
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_one_attached :image
  validates_presence_of :make, :model, :color, :vin, :wholesaleprice, :image
  validates_numericality_of :wholesaleprice, greater_than_or_equal_to:0

  def full_car
    "#{vin} - #{make} #{model}"
  end

  def car_box
    "#{color} #{make} #{model}"
  end

  before_create :add_default_car_img, on: [:create, :update]

  private def add_default_car_img
    unless image.attached?
      self.image.attach(io: File.open('app/assets/images/inception images/default-car.jpg'), filename: 'default-car.jpg', content_type: 'image/jpg')
    end
    
  end

end

app/models/customer.rb
class Customer < ApplicationRecord

  def full_name
    "#{firstname} #{lastname}"
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
end

app/models/loan.rb
class Loan < ApplicationRecord
  validates_numericality_of :interestrate, greater_than_or_equal_to:0

  YEARS = %i[3 4 5]

  def full_name
    "#{year} years - #{interestrate * 100}%"
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :customer
  belongs_to :user
  belongs_to :car
  belongs_to :loan

  def helper
    wholesale = wholesaleprice
  end

  def sold_to_string
    sold ? 'Sold' : 'Not Sold'
  end

  def self.calc_final_price(car_id, loan_id)
    car = Car.find(car_id)
    loan = Loan.find(loan_id)

    principle = car.wholesaleprice
    rate = loan.interestrate
    years = loan.year

    r = rate / 4;
    n = years * 4;

    markupPrice = principle * 1.082
    taxPrice = markupPrice * 1.043

    total_price = taxPrice*((1+r)**n)

    return total_price
  end

  def sum
    inject(0) { |sum, x| sum + x }
  end
end

app/models/quotesold.rb
class Quotesold < ApplicationRecord

end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
# This currently has no functionality, but is a shell for advanced search.
  def search_cars

    cars = Car.all

    cars = cars.where(["name LIKE ?","%#{keyword}%"]) if keyword.present?
    cars = cars.where(["make LIKE ?", make]) if make.present?
    cars = cars.where(["model LIKE ?", model]) if model.present?
    cars = cars.where(["color LIKE ?", color]) if color.present?
    cars = cars.where(["wholesaleprice >= ?", minprice]) if minprice.present?
    cars = cars.where(["wholesaleprice >= ?", maxprice]) if maxprice.present?
    cars = cars.where(["vin LIKE ?", vin]) if vin.present?

    return cars
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_presence_of :firstname, :lastname, :email, :role


  ROLES = %i[admin dealership_owner sales_person sales_manager finance_manager inventory_manager]

  def full_name
    "#{firstname} #{lastname}"
  end


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  load_and_authorize_resource
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all.paginate(:per_page =>15, :page => params[:page]).where(["make LIKE ?","%#{params[:make_search]}%"]).where(["model LIKE ?","%#{params[:model_search]}%"]).where(["color LIKE ?","%#{params[:color_search]}%"]).order(:make).paginate(:page => params[:page])
  end

  def wholesale_price
    wholesaleprice = Car.find(params[:id])
    render json: wholesaleprice
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:image, :vin, :color, :make, :model, :wholesaleprice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <thead>
    </thead>
    <tbody>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Image:" %></td>
          <td><%= form.file_field :image %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "VIN #: " %></td>
          <td><%= form.text_field :vin %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Color: " %></td>
          <td><%= form.text_field :color %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Make: " %></td>
          <td><%= form.text_field :make %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Model: " %></td>
          <td><%= form.text_field :model %></td>
        </div>
      </tr>
      <tr class="spaceUnder">
        <div class="field">
          <td><%= form.label "Wholesale Price:" %></td>
          <td><%= form.text_field :wholesaleprice %></td>
        </div>
      </tr>
    </tbody>
  </table>
  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>
<div id="leftbutton"><%= link_to 'New Car', new_car_path %></div>
<div id="search">
  <%= form_tag cars_path, :method => 'get' do %>
    <%= text_field_tag :make_search, params[:make_search], :placeholder => "Make" %>
    <%= text_field_tag :model_search, params[:model_search], :placeholder => "Model"  %>
    <%= text_field_tag :color_search, params[:color_search], :placeholder => "Color"  %>
    <%= submit_tag "Search" %>
  <% end %>
</div>
<br/>
<%=will_paginate @cars %>
<br />
  <% @cars.each do |car| %>
        <% if false %>
          # Add this back if you have to remove it
          <td><%=image_tag(car.image, style: 'width:140px;height:100px;')%></td>
        <% end %>
  <div class="center">
    <div class="col-md-2 column productbox">
      <div class="img-responsive"><%=image_tag(car.image, style: 'width:140px;height:100px;')%></div>
      <div class="producttitle"><%=car.car_box %></div>
      <div class="producttitle">VIN: <%=car.vin %></div>
      <div class="productprice"><div class="pull-right">
        <div class="pure-menu pure-menu-horizontal">
          <ul class="pure-menu-list">
            <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
              <a href="#" id="menuLink1" class="pure-menu-link">Options</a>
              <ul class="pure-menu-children">
                <li class="pure-menu-item"><%= link_to 'Show', car %></li>
                <% if can? :manage, Car %>
                <li class="pure-menu-item"><%= link_to 'Edit', edit_car_path(car) %></li>
                <li class="pure-menu-item"><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div><div class="pricetext"><%= number_to_currency(car.wholesaleprice) %></div></div>
    </div>
  </div>
  <% end %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @car.image, style: 'width:500px;height500px;'%>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Wholesaleprice:</strong>
  <%= number_to_currency(@car.wholesaleprice) %>
</p>

<% if can? :manage, Car %>
<%= link_to 'Edit', edit_car_path(@car) %>|
  <% end %>
<%= link_to 'Back', cars_path %>